# Generated by Django 5.0.3 on 2024-04-03 11:10

import django.db.models.deletion
import jsonfield.fields
import sqlalchemy.sql._elements_constructors
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('annee', models.CharField(max_length=255, null=True)),
                ('type_loi', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=sqlalchemy.sql._elements_constructors.true)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='docs.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_data', jsonfield.fields.JSONField()),
                ('document_split', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='docs.documentsplit')),
            ],
        ),
    ]
